apiVersion: v1
kind: Namespace
metadata:
  name: k8s-spring-boot-apps
---
apiVersion: v1
kind: Namespace
metadata:
  name: k8s-logging
---
apiVersion: v1
kind: Namespace
metadata:
  name: k8s-monitoring
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0001
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1.5Gi
  hostPath:
    path: /data/pv000x/
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0002
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1.5Gi
  hostPath:
    path: /data/pv000x/
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0010
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /data/pv0010/
