apiVersion: v1
kind: Namespace
metadata:
  name: k8s-spring-boot-apps
---
apiVersion: v1
kind: Namespace
metadata:
  name: k8s-logging
---
apiVersion: v1
kind: Namespace
metadata:
  name: k8s-monitoring
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0001
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 16Gi
  hostPath:
    path: /data/pv0001/
