kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: k8s-spring-boot-apps
  name: namespace-reader
rules:
  - apiGroups: ["", "extensions", "apps"]
    resources: ["namespaces", "configmaps", "pods", "services", "endpoints", "secrets"]
    verbs: ["get", "list", "watch"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: namespace-reader-binding
  namespace: k8s-spring-boot-apps
subjects:
- kind: ServiceAccount
  name: default
  namespace: k8s-spring-boot-apps
  apiGroup: ""
roleRef:
  kind: Role
  name: namespace-reader
  apiGroup: "rbac.authorization.k8s.io"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: k8s-be
  namespace: k8s-spring-boot-apps
data:
  application.yml: |-
    k8s-be:
      message: "Message in a bottle"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-be
  namespace: k8s-spring-boot-apps
spec:
  replicas: 2
  selector:
    matchLabels:
      app: k8s-be
  template:
    metadata:
      labels:
        app: k8s-be
        fluentd-log-format: spring-boot-json
      annotations:
           prometheus.io/scrape: 'true'
           prometheus.io/path: '/actuator/prometheus'
           prometheus.io/port: '8010'
    spec:
      containers:
      - name: k8s-be-container
        image: gcr.io/handy-zephyr-272321/k8s-be:1.0.1
        ports:
        - name: service
          containerPort: 80
        - name: management
          containerPort: 8010
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8010
          timeoutSeconds: 5
          periodSeconds: 30
          successThreshold: 1
          failureThreshold: 1
---
apiVersion: v1
kind: Service
metadata:
  name: k8s-be
  namespace: k8s-spring-boot-apps
  labels:
    sba-monitored: "true"
spec:
  type: NodePort
  selector:
    app: k8s-be
  ports:
  - port: 80
    name: service
    nodePort: 30001
  - port: 8010
    name: management
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-bff
  namespace: k8s-spring-boot-apps
spec:
  replicas: 2
  selector:
    matchLabels:
      app: k8s-bff
  template:
    metadata:
      labels:
        app: k8s-bff
        fluentd-log-format: spring-boot-json
      annotations:
           prometheus.io/scrape: 'true'
           prometheus.io/path: '/actuator/prometheus'
           prometheus.io/port: '8010'
    spec:
      containers:
      - name: k8s-bff-container
        image: gcr.io/handy-zephyr-272321/k8s-bff:1.0.0
        ports:
        - name: service
          containerPort: 80
        - name: management
          containerPort: 8010
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8010
          timeoutSeconds: 5
          periodSeconds: 30
          successThreshold: 1
          failureThreshold: 1
---
apiVersion: v1
kind: Service
metadata:
  name: k8s-bff
  namespace: k8s-spring-boot-apps
  labels:
    sba-monitored: "true"
spec:
  type: NodePort
  selector:
    app: k8s-bff
  ports:
  - port: 80
    name: service
    nodePort: 30002
  - port: 8010
    name: management
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: k8s-sba
  namespace: k8s-spring-boot-apps
data:
  application.yml: |-
    spring:
     cloud:
      kubernetes:
        discovery:
          primary-port-name: management
          service-labels:
            sba-monitored: true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-sba
  namespace: k8s-spring-boot-apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-sba
  template:
    metadata:
      labels:
        app: k8s-sba
        fluentd-log-format: spring-boot-json
      annotations:
           prometheus.io/scrape: 'true'
           prometheus.io/path: '/actuator/prometheus'
           prometheus.io/port: '8010'
    spec:
      containers:
      - name: k8s-sba-container
        image: gcr.io/handy-zephyr-272321/k8s-sba:1.0.0
        ports:
        - name: service
          containerPort: 80
        - name: management
          containerPort: 8010
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8010
          timeoutSeconds: 5
          periodSeconds: 30
          successThreshold: 1
          failureThreshold: 1
---
apiVersion: v1
kind: Service
metadata:
  name: k8s-sba
  namespace: k8s-spring-boot-apps
  labels:
    sba-monitored: "true"
spec:
  type: NodePort
  selector:
    app: k8s-sba
  ports:
  - port: 80
    name: service
    nodePort: 30003
  - port: 8010
    name: management
