server:
  port: 80
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYSk8s-be:
  message: "Message from embedded application.yml"